# Use an official PHP runtime as a parent image
FROM php:8.0-apache

# Install Node.js and npm
RUN apt-get update && \
    apt-get install -y nodejs npm

# Set the working directory to /var/www/html
WORKDIR /var/www/html

# Copy the current directory contents into the container at /var/www/html
COPY . /var/www/html

# Install PHP dependencies
RUN apt-get install -y \
    # Add any other PHP dependencies you may need
    RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
    RUN apt-get update && apt-get upgrade -y
# Install npm dependencies and build assets
RUN npm install
RUN npm run production

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
#ENV NAME World

# Run app.py when the container launches
#CMD ["apache2-foreground"]